import type { Metadata } from "next";
import Header from "@/components/Header";
import Footer from "@/components/Footer";

export const metadata: Metadata = { title: "Disclaimer" };

export default function DisclaimerPage() {
  return (
    <div className="flex min-h-screen flex-col bg-white dark:bg-neutral-900">
      <Header />

      <main className="flex-1">
        <div className="mx-auto max-w-4xl px-8 py-24">

          <h1 className="text-5xl tracking-tight text-gray-900 dark:text-gray-100" style={{ fontWeight: 500 }}>
            Disclaimer
          </h1>
          <p className="mt-4 text-sm text-gray-400">
            Effective Date: February 1, 2026 &nbsp;·&nbsp; Last Updated: February 14, 2026
          </p>

          <div className="mt-16 flex flex-col gap-16 text-base leading-relaxed text-gray-600 dark:text-gray-400">

            {/* 1 */}
            <section>
              <h2 className="text-2xl text-gray-900 dark:text-gray-100" style={{ fontWeight: 500 }}>1. General Disclaimer</h2>
              <p className="mt-4">
                The information, content, tools, simulations, predictions, data, and all other materials provided through VARL Inc.&apos;s (&ldquo;VARL,&rdquo; &ldquo;we,&rdquo; &ldquo;us,&rdquo; or &ldquo;our&rdquo;) website at varl.com, application programming interface (&ldquo;API&rdquo;), platform, and related services (collectively, the &ldquo;Services&rdquo;) are provided on an &ldquo;as is&rdquo; and &ldquo;as available&rdquo; basis without warranties of any kind, whether express, implied, statutory, or otherwise.
              </p>
              <p className="mt-4">
                To the fullest extent permitted by applicable law, VARL expressly disclaims all warranties, including but not limited to implied warranties of merchantability, fitness for a particular purpose, non-infringement, accuracy, completeness, reliability, and availability. No advice or information, whether oral or written, obtained from VARL or through the Services shall create any warranty not expressly stated herein.
              </p>
            </section>

            {/* 2 */}
            <section>
              <h2 className="text-2xl text-gray-900 dark:text-gray-100" style={{ fontWeight: 500 }}>2. Not Medical Advice</h2>
              <p className="mt-4">
                Nothing contained in the Services constitutes medical advice, clinical guidance, diagnosis, or treatment recommendation. The outputs generated by VARL&apos;s platform, including but not limited to digital twin simulations, biomarker analyses, predictive models, and drug target identifications, are computational outputs intended for research and informational purposes only.
              </p>
              <p className="mt-4">
                The Services are not a substitute for professional medical judgment, clinical evaluation, or the advice of a qualified healthcare provider. No patient care decision should be made solely on the basis of information or outputs obtained from the VARL platform. Healthcare professionals who utilize VARL&apos;s tools as part of their clinical workflow retain full and sole responsibility for all patient care decisions.
              </p>
              <p className="mt-4">
                VARL does not practice medicine, does not hold itself out as a healthcare provider, and does not establish a physician-patient or provider-patient relationship with any individual through the provision of its Services.
              </p>
            </section>

            {/* 3 */}
            <section>
              <h2 className="text-2xl text-gray-900 dark:text-gray-100" style={{ fontWeight: 500 }}>3. Not Financial or Investment Advice</h2>
              <p className="mt-4">
                The information presented on our website, including but not limited to the Investors page, financial reports, earnings summaries, pipeline disclosures, and shareholder communications, is provided for general informational purposes only. None of this information constitutes an offer to sell, a solicitation of an offer to buy, or a recommendation of any security, investment product, or investment strategy.
              </p>
              <p className="mt-4">
                All financial data, projections, forward-looking statements, and performance metrics are subject to risks, uncertainties, and assumptions that could cause actual results to differ materially from those expressed or implied. Past performance is not indicative of future results. Investors should conduct their own due diligence and consult with qualified financial advisors before making any investment decisions.
              </p>
              <p className="mt-4">
                VARL, its officers, directors, employees, and affiliates disclaim any and all liability for investment decisions made based on information provided through the Services.
              </p>
            </section>

            {/* 4 */}
            <section>
              <h2 className="text-2xl text-gray-900 dark:text-gray-100" style={{ fontWeight: 500 }}>4. Research and Simulation Outputs</h2>
              <p className="mt-4">
                All simulation results, predictions, analyses, and computational outputs generated by the VARL platform are based on mathematical models, statistical algorithms, and machine learning systems that operate on available data. These outputs are probabilistic in nature and subject to inherent limitations, including but not limited to data quality, model assumptions, computational approximations, and the irreducible complexity of biological systems.
              </p>
              <p className="mt-4">
                VARL does not guarantee the accuracy, completeness, or clinical applicability of any simulation result. Digital twin models are approximations of biological reality, not exact replicas. Predictions generated by our platform should be treated as hypotheses requiring independent experimental validation, not as established scientific facts.
              </p>
              <p className="mt-4">
                Users of the platform assume full responsibility for the interpretation and application of all outputs. VARL shall not be liable for any consequences arising from decisions made based on platform outputs, including but not limited to failed experiments, adverse clinical outcomes, regulatory actions, or financial losses.
              </p>
            </section>

            {/* 5 */}
            <section>
              <h2 className="text-2xl text-gray-900 dark:text-gray-100" style={{ fontWeight: 500 }}>5. Forward-Looking Statements</h2>
              <p className="mt-4">
                Certain statements contained on our website and in our publications constitute &ldquo;forward-looking statements&rdquo; within the meaning of the Private Securities Litigation Reform Act of 1995 and applicable securities laws. These statements may include, without limitation, projections regarding revenue, pipeline progress, research milestones, market opportunities, technology development, partnership outcomes, and strategic plans.
              </p>
              <p className="mt-4">
                Forward-looking statements are identified by the use of words such as &ldquo;anticipate,&rdquo; &ldquo;believe,&rdquo; &ldquo;estimate,&rdquo; &ldquo;expect,&rdquo; &ldquo;intend,&rdquo; &ldquo;plan,&rdquo; &ldquo;project,&rdquo; &ldquo;will,&rdquo; &ldquo;may,&rdquo; &ldquo;should,&rdquo; and similar expressions. These statements are based on current expectations and assumptions that are subject to significant risks and uncertainties, including but not limited to:
              </p>
              <ul className="mt-4 flex flex-col gap-2 pl-6">
                <li className="list-disc">Changes in regulatory environments affecting biological research and drug development</li>
                <li className="list-disc">Technological risks inherent in computational biology and artificial intelligence</li>
                <li className="list-disc">Uncertainty in the outcome of clinical validation studies and peer review processes</li>
                <li className="list-disc">Competitive developments in the biological intelligence and pharmaceutical sectors</li>
                <li className="list-disc">Dependence on key personnel, including the co-founders</li>
                <li className="list-disc">Risks associated with intellectual property protection and enforcement</li>
                <li className="list-disc">Macroeconomic conditions, geopolitical instability, and public health events</li>
                <li className="list-disc">Changes in the availability of funding, partnerships, or market conditions</li>
              </ul>
              <p className="mt-4">
                Actual results may differ materially from those indicated in any forward-looking statement. VARL undertakes no obligation to update or revise any forward-looking statement, whether as a result of new information, future events, or otherwise, except as required by applicable law.
              </p>
            </section>

            {/* 6 */}
            <section>
              <h2 className="text-2xl text-gray-900 dark:text-gray-100" style={{ fontWeight: 500 }}>6. Intellectual Property</h2>
              <p className="mt-4">
                All content, software, algorithms, models, data formats, documentation, trademarks, logos, trade names, and other intellectual property displayed on or accessible through the Services are the exclusive property of VARL Inc. or its licensors, and are protected by United States and international copyright, trademark, patent, trade secret, and other intellectual property or proprietary rights laws.
              </p>
              <p className="mt-4">
                No part of the Services may be reproduced, distributed, modified, transmitted, reused, downloaded, displayed, posted, performed, or used in any form or by any means without the prior written permission of VARL, except as expressly permitted under the terms of an applicable license agreement.
              </p>
              <p className="mt-4">
                Unauthorized use of any VARL intellectual property may result in civil liability and criminal prosecution to the maximum extent permitted by law.
              </p>
            </section>

            {/* 7 */}
            <section>
              <h2 className="text-2xl text-gray-900 dark:text-gray-100" style={{ fontWeight: 500 }}>7. Limitation of Liability</h2>
              <p className="mt-4">
                To the maximum extent permitted by applicable law, in no event shall VARL, its officers, directors, employees, agents, affiliates, successors, or assigns be liable for any indirect, incidental, special, consequential, exemplary, or punitive damages, including but not limited to damages for loss of profits, goodwill, data, use, or other intangible losses, arising out of or in connection with:
              </p>
              <ul className="mt-4 flex flex-col gap-2 pl-6">
                <li className="list-disc">Your access to, use of, or inability to access or use the Services</li>
                <li className="list-disc">Any conduct or content of any third party on or related to the Services</li>
                <li className="list-disc">Any content obtained from the Services, including simulation outputs, predictions, or analyses</li>
                <li className="list-disc">Unauthorized access, use, or alteration of your transmissions or data</li>
                <li className="list-disc">Errors, inaccuracies, or omissions in any content or output provided through the Services</li>
                <li className="list-disc">Any interruption, suspension, or termination of the Services, whether voluntary or involuntary</li>
                <li className="list-disc">Any bugs, viruses, or other harmful code that may be transmitted through the Services</li>
              </ul>
              <p className="mt-4">
                In no event shall VARL&apos;s total aggregate liability to you for all claims arising out of or relating to the use of or inability to use the Services exceed the greater of (a) the amount you have paid to VARL during the twelve (12) months immediately preceding the event giving rise to the claim, or (b) one hundred United States dollars ($100.00).
              </p>
              <p className="mt-4">
                The limitations of liability set forth herein shall apply regardless of the form of action, whether the claim is based on contract, tort (including negligence), strict liability, statute, or any other legal or equitable theory, and whether or not VARL has been advised of the possibility of such damages.
              </p>
            </section>

            {/* 8 */}
            <section>
              <h2 className="text-2xl text-gray-900 dark:text-gray-100" style={{ fontWeight: 500 }}>8. Indemnification</h2>
              <p className="mt-4">
                You agree to indemnify, defend, and hold harmless VARL, its officers, directors, employees, agents, affiliates, successors, and assigns from and against any and all claims, damages, obligations, losses, liabilities, costs, and expenses (including but not limited to reasonable attorneys&apos; fees) arising out of or in connection with: (a) your use of the Services; (b) your violation of any term of this Disclaimer or any applicable law or regulation; (c) your violation of any third-party right, including any intellectual property, privacy, or contractual right; or (d) any claim that your use of the Services caused damage to a third party.
              </p>
              <p className="mt-4">
                This indemnification obligation shall survive the termination of your access to the Services and any agreement between you and VARL.
              </p>
            </section>

            {/* 9 */}
            <section>
              <h2 className="text-2xl text-gray-900 dark:text-gray-100" style={{ fontWeight: 500 }}>9. Third-Party Content and Links</h2>
              <p className="mt-4">
                The Services may contain links to third-party websites, references to third-party publications, or integrations with third-party services. VARL does not endorse, control, or assume responsibility for any third-party content, products, or services. The inclusion of any link or reference does not imply affiliation, endorsement, or approval by VARL.
              </p>
              <p className="mt-4">
                Your interactions with any third party found on or through the Services are solely between you and the third party. VARL shall not be liable for any damage or loss caused or alleged to be caused by or in connection with the use of or reliance on any third-party content, products, or services.
              </p>
            </section>

            {/* 10 */}
            <section>
              <h2 className="text-2xl text-gray-900 dark:text-gray-100" style={{ fontWeight: 500 }}>10. Regulatory Status</h2>
              <p className="mt-4">
                VARL&apos;s platform and related tools have not been evaluated, approved, or cleared by the U.S. Food and Drug Administration (FDA), the European Medicines Agency (EMA), or any other national or international regulatory authority for use as a medical device, diagnostic tool, or clinical decision support system, unless explicitly stated otherwise in writing.
              </p>
              <p className="mt-4">
                The Services are intended for research use only (&ldquo;RUO&rdquo;) unless a specific product or feature has received regulatory clearance or approval, in which case the approved indications and limitations of use will be clearly stated in the applicable product documentation.
              </p>
            </section>

            {/* 11 */}
            <section>
              <h2 className="text-2xl text-gray-900 dark:text-gray-100" style={{ fontWeight: 500 }}>11. No Guarantee of Availability</h2>
              <p className="mt-4">
                VARL does not guarantee that the Services will be available at all times, uninterrupted, secure, or error-free. We reserve the right to modify, suspend, or discontinue any part of the Services at any time, with or without notice, for any reason. We shall not be liable to you or any third party for any modification, suspension, or discontinuation of the Services.
              </p>
              <p className="mt-4">
                Scheduled maintenance windows will be communicated in advance where practicable. However, emergency maintenance, security patches, and infrastructure updates may be performed without prior notice when necessary to protect the integrity of the platform.
              </p>
            </section>

            {/* 12 */}
            <section>
              <h2 className="text-2xl text-gray-900 dark:text-gray-100" style={{ fontWeight: 500 }}>12. Biosecurity and Dual-Use Considerations</h2>
              <p className="mt-4">
                VARL acknowledges that certain capabilities of its platform could theoretically be misused for purposes that are harmful to public health, national security, or biosafety. While we implement rigorous access controls, usage monitoring, and institutional review processes, we cannot guarantee that all risks of misuse will be eliminated.
              </p>
              <p className="mt-4">
                Users of the platform agree not to use the Services for any purpose that violates applicable law, threatens public safety, or contravenes the intended research and therapeutic applications of the platform. VARL reserves the right to immediately terminate access for any user whose activity is deemed to pose a biosecurity risk, without prior notice and without liability.
              </p>
              <p className="mt-4">
                VARL cooperates with relevant governmental and international bodies on matters of biosecurity and dual-use research of concern. We report suspected misuse to appropriate authorities as required or permitted by law.
              </p>
            </section>

            {/* 13 */}
            <section>
              <h2 className="text-2xl text-gray-900 dark:text-gray-100" style={{ fontWeight: 500 }}>13. Publication and Citation Disclaimer</h2>
              <p className="mt-4">
                Scientific publications referenced on our website, including those authored by VARL employees or collaborators, represent the views and findings of their respective authors at the time of publication. They do not necessarily reflect the current position, capabilities, or commercial offerings of VARL Inc.
              </p>
              <p className="mt-4">
                Research findings are subject to ongoing peer review, replication, and revision. No publication should be interpreted as a guarantee of any specific platform capability, clinical outcome, or commercial product feature.
              </p>
            </section>

            {/* 14 */}
            <section>
              <h2 className="text-2xl text-gray-900 dark:text-gray-100" style={{ fontWeight: 500 }}>14. Severability</h2>
              <p className="mt-4">
                If any provision of this Disclaimer is held to be invalid, illegal, or unenforceable by a court of competent jurisdiction, such provision shall be modified to the minimum extent necessary to make it valid, legal, and enforceable, or if modification is not possible, shall be severed from this Disclaimer. The invalidity, illegality, or unenforceability of any provision shall not affect the validity, legality, or enforceability of the remaining provisions, which shall continue in full force and effect.
              </p>
            </section>

            {/* 15 */}
            <section>
              <h2 className="text-2xl text-gray-900 dark:text-gray-100" style={{ fontWeight: 500 }}>15. Governing Law</h2>
              <p className="mt-4">
                This Disclaimer shall be governed by and construed in accordance with the laws of the State of Delaware, United States, without regard to its conflict of law provisions. Any legal action or proceeding arising out of or relating to this Disclaimer shall be brought exclusively in the federal or state courts located in Wilmington, Delaware, and you consent to the personal jurisdiction and venue of such courts.
              </p>
            </section>

            {/* 16 */}
            <section>
              <h2 className="text-2xl text-gray-900 dark:text-gray-100" style={{ fontWeight: 500 }}>16. Entire Agreement</h2>
              <p className="mt-4">
                This Disclaimer, together with our Privacy Policy, Terms of Use, Cookie Policy, and any applicable service-specific agreements, constitutes the entire agreement between you and VARL with respect to the subject matter hereof and supersedes all prior or contemporaneous communications, representations, or agreements, whether oral or written.
              </p>
            </section>

            {/* 17 */}
            <section>
              <h2 className="text-2xl text-gray-900 dark:text-gray-100" style={{ fontWeight: 500 }}>17. Contact</h2>
              <p className="mt-4">
                If you have any questions about this Disclaimer, please contact:
              </p>
              <div className="mt-6 rounded-xl bg-gray-50 p-8 dark:bg-neutral-800">
                <div className="flex flex-col gap-4 text-sm">
                  <div>
                    <span className="text-xs tracking-wide text-gray-400" style={{ fontWeight: 500 }}>Legal Department</span>
                    <p className="mt-1 text-gray-900 dark:text-gray-100">VARL Inc.</p>
                  </div>
                  <div>
                    <span className="text-xs tracking-wide text-gray-400" style={{ fontWeight: 500 }}>Email</span>
                    <p className="mt-1 text-gray-900 dark:text-gray-100">legal@varl.com</p>
                  </div>
                  <div>
                    <span className="text-xs tracking-wide text-gray-400" style={{ fontWeight: 500 }}>Mailing Address</span>
                    <p className="mt-1 text-gray-900 dark:text-gray-100">VARL Inc., 1209 Orange Street, Wilmington, DE 19801, United States</p>
                  </div>
                </div>
              </div>
            </section>

            {/* Closing */}
            <section className="border-t border-gray-200 pt-8 dark:border-neutral-800">
              <p className="text-sm text-gray-400">
                By using the Services, you acknowledge that you have read, understood, and agree to be bound by this Disclaimer in its entirety. If you do not agree to any provision herein, you must immediately discontinue use of the Services.
              </p>
            </section>

          </div>
        </div>
      </main>

      <Footer />
    </div>
  );
}
